/**
 * Image Analyzer — Evaluates uploaded photos for duplicate content, suspicious metadata,
 * and generates perceptual hashes for comparison.
 * Returns a risk sub-score from 0 (no risk) to 100 (maximum suspicion).
 */

import crypto from "crypto";
import fs from "fs/promises";
import path from "path";
import prisma from "@/lib/db";

interface ImageAnalysisResult {
  score: number;
  signals: string[];
  fingerprint: string;
  duplicateMatches: Array<{ photoUrl: string; reportId: string | null; similarity: number }>;
}

/**
 * Generate a simple perceptual-style hash from image file bytes.
 * Uses SHA-256 of the file content as a content-addressable fingerprint.
 * For true perceptual hashing we'd need an image processing library,
 * but content hashing catches exact duplicates and re-uploads effectively.
 */
export function generateImageFingerprint(buffer: Buffer): string {
  return crypto.createHash("sha256").update(buffer).digest("hex").slice(0, 32);
}

/**
 * Check MIME magic bytes match declared type
 */
export function validateMagicBytes(buffer: Buffer, declaredMime: string): boolean {
  if (buffer.length < 4) return false;

  const jpegMagic = buffer[0] === 0xFF && buffer[1] === 0xD8 && buffer[2] === 0xFF;
  const pngMagic = buffer[0] === 0x89 && buffer[1] === 0x50 && buffer[2] === 0x4E && buffer[3] === 0x47;
  const webpMagic = buffer.length >= 12 &&
    buffer[0] === 0x52 && buffer[1] === 0x49 && buffer[2] === 0x46 && buffer[3] === 0x46 &&
    buffer[8] === 0x57 && buffer[9] === 0x45 && buffer[10] === 0x42 && buffer[11] === 0x50;

  if (declaredMime.includes("jpeg") || declaredMime.includes("jpg")) return jpegMagic;
  if (declaredMime.includes("png")) return pngMagic;
  if (declaredMime.includes("webp")) return webpMagic;

  return false;
}

/**
 * Check EXIF/metadata for AI generator signatures
 */
export function checkForAISignatures(buffer: Buffer): string[] {
  const signals: string[] = [];

  // Convert buffer to string for simple text search in metadata
  // EXIF data is embedded as ASCII strings in JPEG/PNG files
  const textContent = buffer.toString("latin1");

  const aiSignatures = [
    "DALL-E", "dall-e", "Midjourney", "midjourney",
    "Stable Diffusion", "stable diffusion", "StableDiffusion",
    "SDXL", "ComfyUI", "A1111", "automatic1111",
    "NovelAI", "Craiyon", "Firefly", "Adobe Firefly",
    "AI Generated", "ai-generated", "artificially generated",
    "Generated by AI", "dream studio", "DreamStudio",
    "leonardo.ai", "playground.ai", "nightcafe",
  ];

  for (const sig of aiSignatures) {
    if (textContent.includes(sig)) {
      signals.push(`AI generator signature found in metadata: "${sig}"`);
    }
  }

  return signals;
}

/**
 * Strip potentially dangerous or privacy-sensitive EXIF metadata
 * while preserving useful GPS data for location verification.
 * 
 * Note: Full EXIF stripping requires a library like sharp or exiftool.
 * This function documents what should be stripped and returns warnings.
 */
export function analyzeMetadataPrivacy(buffer: Buffer): string[] {
  const warnings: string[] = [];
  const textContent = buffer.toString("latin1");

  // Check for embedded personal info patterns
  if (/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/.test(textContent)) {
    warnings.push("Email address found in image metadata");
  }

  // Check for device serial numbers (common pattern in EXIF)
  if (/SerialNumber/i.test(textContent)) {
    warnings.push("Device serial number present in metadata");
  }

  return warnings;
}

/**
 * Find duplicate images by comparing fingerprint against database
 */
async function findDuplicates(
  fingerprint: string,
  excludeReportId?: string
): Promise<Array<{ photoUrl: string; reportId: string | null; similarity: number }>> {
  try {
    const matches = await prisma.photoFingerprint.findMany({
      where: {
        fingerprint,
        ...(excludeReportId ? { reportId: { not: excludeReportId } } : {}),
      },
      take: 5,
      orderBy: { createdAt: "desc" },
    });

    return matches.map((m) => ({
      photoUrl: m.photoUrl,
      reportId: m.reportId,
      similarity: 100, // Exact content hash match
    }));
  } catch {
    return [];
  }
}

/**
 * Main image analysis function
 */
export async function analyzeImage(
  photoUrl: string,
  declaredMime: string,
  userId: string,
  reportId?: string
): Promise<ImageAnalysisResult> {
  const signals: string[] = [];
  let score = 0;
  let fingerprint = "";
  let duplicateMatches: Array<{ photoUrl: string; reportId: string | null; similarity: number }> = [];

  try {
    // Read the file from disk
    const filePath = path.join(process.cwd(), "public", photoUrl.replace(/^\//, ""));
    const buffer = await fs.readFile(filePath);

    // 1. Generate fingerprint
    fingerprint = generateImageFingerprint(buffer);

    // 2. Validate magic bytes
    if (!validateMagicBytes(buffer, declaredMime)) {
      score += 30;
      signals.push("File magic bytes do not match declared MIME type — possible file manipulation");
    }

    // 3. Check for AI generator signatures in metadata
    const aiSigs = checkForAISignatures(buffer);
    if (aiSigs.length > 0) {
      score += Math.min(aiSigs.length * 15, 40);
      signals.push(...aiSigs);
    }

    // 4. Check for duplicate images across reports
    duplicateMatches = await findDuplicates(fingerprint, reportId);
    if (duplicateMatches.length > 0) {
      score += Math.min(duplicateMatches.length * 20, 40);
      signals.push(`Image matches ${duplicateMatches.length} previously uploaded photo(s)`);
    }

    // 5. Check for same-user duplicate usage
    const userDuplicates = await prisma.photoFingerprint.findMany({
      where: { fingerprint, uploaderId: userId },
      take: 3,
    });
    if (userDuplicates.length > 0) {
      score += 15;
      signals.push("User has uploaded the same image in a previous report");
    }

    // 6. Suspiciously small file (could be a placeholder/generated thumbnail)
    if (buffer.length < 5000) {
      score += 15;
      signals.push("Unusually small image file (< 5KB) — possible placeholder");
    }

    // 7. Privacy metadata check (informational, not scored)
    const privacyWarnings = analyzeMetadataPrivacy(buffer);
    // These are logged but don't affect score

    // 8. Save fingerprint record
    await prisma.photoFingerprint.create({
      data: {
        photoUrl,
        fingerprint,
        uploaderId: userId,
        reportId: reportId || null,
        fileSize: buffer.length,
        mimeType: declaredMime,
      },
    });
  } catch (error) {
    console.error("Image analysis error:", error);
    // Don't penalize for analysis errors
  }

  return {
    score: Math.min(score, 100),
    signals,
    fingerprint,
    duplicateMatches,
  };
}
